-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS test5.postal DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.address DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.address DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.payments DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.services DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.bookings DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.bookings DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.transport_booking DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.transport_booking DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.transport_booking DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.transport_booking DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.bus_stand DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.bus DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.bus DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.bus_class DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.train_station DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.train DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.train DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.train_class DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.flight DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.flight DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.flight_class DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.airport DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.accommodation_booking DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.accommodation_booking DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.accommodation_booking DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.room_booking DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.room_booking DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.room DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.room DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.room DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.user_email DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.train_info DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.flight_info DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS test5.bus_info DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS test5.users;

CREATE TABLE IF NOT EXISTS test5.users
(
    user_id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    mobile_no character varying(20) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY (user_id),
    UNIQUE (mobile_no),
    UNIQUE (password)
);

DROP TABLE IF EXISTS test5.location;

CREATE TABLE IF NOT EXISTS test5.location
(
    location_id character varying(20) NOT NULL,
    city character varying(100) NOT NULL,
    state character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    PRIMARY KEY (location_id)
);

DROP TABLE IF EXISTS test5.agency;

CREATE TABLE IF NOT EXISTS test5.agency
(
    agency_id integer NOT NULL,
    agency_name character varying(100) NOT NULL,
    agency_email character varying(100) NOT NULL,
    agency_website character varying(100) NOT NULL,
    commission_rate double precision NOT NULL,
    PRIMARY KEY (agency_id),
    UNIQUE (agency_name, agency_email)
);

DROP TABLE IF EXISTS test5.postal;

CREATE TABLE IF NOT EXISTS test5.postal
(
    postal_code integer NOT NULL,
    location_id character varying(20) NOT NULL,
    PRIMARY KEY (postal_code)
);

DROP TABLE IF EXISTS test5.address;

CREATE TABLE IF NOT EXISTS test5.address
(
    agency_id integer NOT NULL,
    postal_code integer NOT NULL,
    local_address character varying(200) NOT NULL,
    PRIMARY KEY (agency_id, postal_code)
);

DROP TABLE IF EXISTS test5.payments;

CREATE TABLE IF NOT EXISTS test5.payments
(
    payment_id integer NOT NULL,
    user_id integer NOT NULL,
    payment_method character varying(100) NOT NULL,
    payment_date date NOT NULL,
    status character varying(100) NOT NULL,
    PRIMARY KEY (payment_id)
);

DROP TABLE IF EXISTS test5.services;

CREATE TABLE IF NOT EXISTS test5.services
(
    service_id integer NOT NULL,
    agency_id integer NOT NULL,
    service_name character varying(50) NOT NULL,
    PRIMARY KEY (service_id)
);

DROP TABLE IF EXISTS test5.bookings;

CREATE TABLE IF NOT EXISTS test5.bookings
(
    booking_id integer NOT NULL,
    user_id integer NOT NULL,
    payment_id integer NOT NULL,
    booking_date date NOT NULL,
    total_amount double precision NOT NULL,
    PRIMARY KEY (booking_id)
);

DROP TABLE IF EXISTS test5.transport_booking;

CREATE TABLE IF NOT EXISTS test5.transport_booking
(
    booking_id integer NOT NULL,
    service_id integer NOT NULL,
    departure_location_id character varying(20) NOT NULL,
    arrival_location_id character varying(20) NOT NULL,
    journey_date date NOT NULL,
    ticket_no character varying(20) NOT NULL,
    seat_no character varying(10) NOT NULL,
    PRIMARY KEY (booking_id)
);

DROP TABLE IF EXISTS test5.bus_stand;

CREATE TABLE IF NOT EXISTS test5.bus_stand
(
    location_id character varying(20) NOT NULL,
    location_name character varying(50) NOT NULL,
    PRIMARY KEY (location_id)
);

DROP TABLE IF EXISTS test5.bus;

CREATE TABLE IF NOT EXISTS test5.bus
(
    bus_id character varying(20) NOT NULL,
    stand_id character varying(20) NOT NULL,
    trip_code character varying(50) NOT NULL,
    arrival_time time with time zone NOT NULL,
    departure_time time with time zone NOT NULL,
    day integer NOT NULL,
    PRIMARY KEY (bus_id, stand_id, trip_code)
);

DROP TABLE IF EXISTS test5.bus_class;

CREATE TABLE IF NOT EXISTS test5.bus_class
(
    bus_class_id character varying(50) NOT NULL,
    bus_id character varying(20) NOT NULL,
    capacity integer NOT NULL,
    price double precision NOT NULL,
    currency character varying(20) NOT NULL,
    PRIMARY KEY (bus_class_id, bus_id)
);

DROP TABLE IF EXISTS test5.train_station;

CREATE TABLE IF NOT EXISTS test5.train_station
(
    location_id character varying(20) NOT NULL,
    station_name character varying(50) NOT NULL,
    PRIMARY KEY (location_id)
);

DROP TABLE IF EXISTS test5.train;

CREATE TABLE IF NOT EXISTS test5.train
(
    train_id character varying(50) NOT NULL,
    station_id character varying(20) NOT NULL,
    trip_code character varying(50) NOT NULL,
    arrival_time time with time zone NOT NULL,
    departure_time time with time zone NOT NULL,
    day integer NOT NULL,
    PRIMARY KEY (train_id, station_id, trip_code)
);

DROP TABLE IF EXISTS test5.train_class;

CREATE TABLE IF NOT EXISTS test5.train_class
(
    train_class_id character varying(50) NOT NULL,
    train_id character varying(50) NOT NULL,
    capacity integer NOT NULL,
    price double precision NOT NULL,
    currency character varying(20) NOT NULL,
    PRIMARY KEY (train_class_id, train_id)
);

DROP TABLE IF EXISTS test5.flight;

CREATE TABLE IF NOT EXISTS test5.flight
(
    flight_code character varying(50) NOT NULL,
    airport_code character varying(20) NOT NULL,
    trip_code character varying(50) NOT NULL,
    arrival_time time with time zone NOT NULL,
    departure_time time with time zone NOT NULL,
    day integer NOT NULL,
    PRIMARY KEY (flight_code, airport_code, trip_code)
);

DROP TABLE IF EXISTS test5.flight_class;

CREATE TABLE IF NOT EXISTS test5.flight_class
(
    flight_class_id character varying(50) NOT NULL,
    flight_code character varying(50) NOT NULL,
    capacity integer NOT NULL,
    price double precision NOT NULL,
    currency character varying(20) NOT NULL,
    PRIMARY KEY (flight_class_id, flight_code)
);

DROP TABLE IF EXISTS test5.airport;

CREATE TABLE IF NOT EXISTS test5.airport
(
    location_id character varying(20) NOT NULL,
    airport_name character varying(50) NOT NULL,
    PRIMARY KEY (location_id)
);

DROP TABLE IF EXISTS test5.accommodation_booking;

CREATE TABLE IF NOT EXISTS test5.accommodation_booking
(
    booking_id integer NOT NULL,
    service_id integer NOT NULL,
    location_id character varying(20) NOT NULL,
    check_in_date date NOT NULL,
    check_out_date date NOT NULL,
    head_count integer NOT NULL,
    PRIMARY KEY (booking_id)
);

DROP TABLE IF EXISTS test5.room_booking;

CREATE TABLE IF NOT EXISTS test5.room_booking
(
    booking_id integer NOT NULL,
    room_id character varying(20) NOT NULL,
    service_id integer NOT NULL,
    PRIMARY KEY (booking_id, room_id, service_id)
);

DROP TABLE IF EXISTS test5.room_class;

CREATE TABLE IF NOT EXISTS test5.room_class
(
    room_class_id character varying(50) NOT NULL,
    class_name character varying(100) NOT NULL,
    price double precision NOT NULL,
    currency character varying(20) NOT NULL,
    PRIMARY KEY (room_class_id)
);

DROP TABLE IF EXISTS test5.room;

CREATE TABLE IF NOT EXISTS test5.room
(
    room_id character varying(20) NOT NULL,
    service_id integer NOT NULL,
    room_class_id character varying(50) NOT NULL,
    location_id character varying(20) NOT NULL,
    status character varying(50) NOT NULL,
    PRIMARY KEY (room_id, service_id)
);

DROP TABLE IF EXISTS test5.user_email;

CREATE TABLE IF NOT EXISTS test5.user_email
(
    user_id integer NOT NULL,
    email_address character varying(100) NOT NULL,
    PRIMARY KEY (user_id, email_address),
    UNIQUE (email_address)
);

DROP TABLE IF EXISTS test5.train_info;

CREATE TABLE IF NOT EXISTS test5.train_info
(
    train_id character varying(50) NOT NULL,
    service_id integer NOT NULL,
    PRIMARY KEY (train_id)
);

DROP TABLE IF EXISTS test5.flight_info;

CREATE TABLE IF NOT EXISTS test5.flight_info
(
    flight_code character varying(50) NOT NULL,
    service_id integer NOT NULL,
    PRIMARY KEY (flight_code)
);

DROP TABLE IF EXISTS test5.bus_info;

CREATE TABLE IF NOT EXISTS test5.bus_info
(
    bus_id character varying(20) NOT NULL,
    service_id integer NOT NULL,
    PRIMARY KEY (bus_id)
);

ALTER TABLE IF EXISTS test5.postal
    ADD FOREIGN KEY (location_id)
    REFERENCES test5.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.address
    ADD FOREIGN KEY (agency_id)
    REFERENCES test5.agency (agency_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.address
    ADD FOREIGN KEY (postal_code)
    REFERENCES test5.postal (postal_code) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.payments
    ADD FOREIGN KEY (user_id)
    REFERENCES test5.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.services
    ADD FOREIGN KEY (agency_id)
    REFERENCES test5.agency (agency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS test5.bookings
    ADD FOREIGN KEY (user_id)
    REFERENCES test5.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.bookings
    ADD FOREIGN KEY (payment_id)
    REFERENCES test5.payments (payment_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.transport_booking
    ADD FOREIGN KEY (departure_location_id)
    REFERENCES test5.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.transport_booking
    ADD FOREIGN KEY (arrival_location_id)
    REFERENCES test5.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.transport_booking
    ADD FOREIGN KEY (service_id)
    REFERENCES test5.services (service_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.transport_booking
    ADD FOREIGN KEY (booking_id)
    REFERENCES test5.bookings (booking_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.bus_stand
    ADD FOREIGN KEY (location_id)
    REFERENCES test5.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.bus
    ADD FOREIGN KEY (stand_id)
    REFERENCES test5.bus_stand (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.bus
    ADD FOREIGN KEY (bus_id)
    REFERENCES test5.bus_info (bus_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.bus_class
    ADD FOREIGN KEY (bus_id)
    REFERENCES test5.bus_info (bus_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.train_station
    ADD FOREIGN KEY (location_id)
    REFERENCES test5.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.train
    ADD FOREIGN KEY (station_id)
    REFERENCES test5.train_station (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.train
    ADD FOREIGN KEY (train_id)
    REFERENCES test5.train_info (train_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.train_class
    ADD FOREIGN KEY (train_id)
    REFERENCES test5.train_info (train_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.flight
    ADD FOREIGN KEY (airport_code)
    REFERENCES test5.airport (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.flight
    ADD FOREIGN KEY (flight_code)
    REFERENCES test5.flight_info (flight_code) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.flight_class
    ADD FOREIGN KEY (flight_code)
    REFERENCES test5.flight_info (flight_code) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.airport
    ADD FOREIGN KEY (location_id)
    REFERENCES test5.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.accommodation_booking
    ADD FOREIGN KEY (location_id)
    REFERENCES test5.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.accommodation_booking
    ADD FOREIGN KEY (booking_id)
    REFERENCES test5.bookings (booking_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.accommodation_booking
    ADD FOREIGN KEY (service_id)
    REFERENCES test5.services (service_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.room_booking
    ADD FOREIGN KEY (booking_id)
    REFERENCES test5.accommodation_booking (booking_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.room_booking
    ADD FOREIGN KEY (room_id, service_id)
    REFERENCES test5.room (room_id, service_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.room
    ADD FOREIGN KEY (location_id)
    REFERENCES test5.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.room
    ADD FOREIGN KEY (room_class_id)
    REFERENCES test5.room_class (room_class_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.room
    ADD FOREIGN KEY (service_id)
    REFERENCES test5.services (service_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.user_email
    ADD FOREIGN KEY (user_id)
    REFERENCES test5.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.train_info
    ADD FOREIGN KEY (service_id)
    REFERENCES test5.services (service_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.flight_info
    ADD FOREIGN KEY (service_id)
    REFERENCES test5.services (service_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS test5.bus_info
    ADD FOREIGN KEY (service_id)
    REFERENCES test5.services (service_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;